let productsData = [
  {
    id: 1,
    title: "Toys",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    src: "images/product-1.png",
    size: "small",
  },
  {
    id: 2,
    title: "Camera",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    size: "large",
    src: "images/product-2.png",
  },
  {
    id: 3,
    title: "Meal",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    size: "small",
    src: "images/product-3.png",
  },
  {
    id: 4,
    title: "Outfit",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    size: "large",
    src: "images/product-4.png",
  },
  {
    id: 5,
    title: "Flowers",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    size: "small",
    src: "images/product-5.png",
  },
  {
    id: 6,
    title: "Cup",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    src: "images/product-6.png",
    size: "small",
  },
  {
    id: 7,
    title: "Labtop",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    src: "images/product-7.png",
    size: "large",
  },
  {
    id: 8,
    title: "Headphone",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    src: "images/product-8.png",
    size: "small",
  },
  {
    id: 9,
    title: "shoes",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    src: "images/product-9.png",
    size: "large",
  },
  {
    id: 10,
    title: "Watch",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    src: "images/product-10.png",
    size: "small",
  },
  {
    id: 11,
    title: "Blocks",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    src: "images/product-11.png",
    size: "large",
  },
  {
    id: 12,
    title: "Sticky notes",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum facilis sapiente t. Illum facilis sapie error est quos ducimus.",
    src: "images/product-12.png",
    size: "small",
  },
];
